[package]
name = "wayper-launcher"
version.workspace = true
edition.workspace = true

[dependencies]
wayper-lib = { path = "../wayper-lib" }
color-eyre.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

strum = { version = "0.27", features = ["derive"] }
